# Generated by Django 4.2.11 on 2026-02-13 15:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('location', models.CharField(blank=True, help_text='City or area, e.g. Johannesburg, Cape Town', max_length=255)),
                ('job_title_target', models.CharField(blank=True, help_text='The type of job you are looking for', max_length=255)),
                ('industries_interested', models.CharField(blank=True, help_text='Comma-separated list of industries', max_length=500)),
                ('salary_expectation_min', models.DecimalField(blank=True, decimal_places=2, help_text='Minimum salary expectation (ZAR per annum)', max_digits=12, null=True)),
                ('salary_expectation_max', models.DecimalField(blank=True, decimal_places=2, help_text='Maximum salary expectation (ZAR per annum)', max_digits=12, null=True)),
                ('willing_to_relocate', models.BooleanField(default=False)),
                ('work_type_preference', models.CharField(choices=[('remote', 'Remote'), ('hybrid', 'Hybrid'), ('onsite', 'On-site'), ('any', 'Any')], default='any', max_length=10)),
                ('years_experience', models.IntegerField(blank=True, help_text='Total years of work experience', null=True)),
                ('skills', models.JSONField(blank=True, default=list, help_text='List of skills as a JSON array')),
                ('automation_consent', models.BooleanField(default=False, help_text='User has agreed to automation terms')),
                ('automation_consent_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
