# Generated by Django 4.2.11 on 2026-02-13 15:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import documents.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(choices=[('cv', 'CV / Resume'), ('cover_letter', 'Cover Letter'), ('certificate', 'Certificate'), ('portfolio', 'Portfolio')], max_length=15)),
                ('title', models.CharField(help_text='Give it a descriptive name, e.g. "Senior Dev CV v3"', max_length=255)),
                ('file', models.FileField(upload_to=documents.models.document_upload_path)),
                ('version', models.CharField(blank=True, default='1.0', help_text='Version number for this document', max_length=20)),
                ('is_active', models.BooleanField(default=True, help_text='Is this the version you want to use for new applications?')),
                ('tags', models.JSONField(blank=True, default=list, help_text='Tags for categorising, e.g. ["tech", "senior", "python"]')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_date'],
            },
        ),
        migrations.CreateModel(
            name='CoverLetterTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('content', models.TextField(help_text='Use placeholders like {company_name}, {job_title}, {your_skills} for auto-filling')),
                ('job_type', models.CharField(blank=True, help_text='What kind of jobs is this template for?', max_length=100)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cover_letter_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-is_default', '-updated_at'],
            },
        ),
    ]
